##############################################
# +----------------------------------------+ #
# |            Wardrobe Settings           | #
# +----------------------------------------+ #
##############################################

wardrobe:
  # What should the back button do.
  # If the player is inside a vault category, it will take them out first.
  back-command: "menu"
  # Button material in the menu. Supports Nexo.
  buttons:
    back: "[nexo] icon_arrow_left_red"
    previous: "[nexo] icon_arrow_left"
    next: "[nexo] icon_arrow_right"
    clear: "[nexo] icon_bin"
  # Define the angle offsets needed for clothing to follow the player's body when sneaking.
  positioning:
    chest:
      sneak-angle: 12.0

##############################################
# +----------------------------------------+ #
# |             Prefix Settings            | #
# +----------------------------------------+ #
##############################################

prefix:
  # The format that wraps the custom prefix.
  format: "&8[{prefix}&r&8]&r "
  # How many prefix slots a player can save.
  slots: 3
  # Allowed characters within prefixes.
  regex: "^[a-zA-Z0-9_:\\- ]+$"
  # How many characters a prefix can be, excluding formatting such as hex codes.
  length: 32
  # Words that are not allowed inside custom prefixes.
  blacklisted-words:
    - owner
    - head-admin
    - admin
    - head-mod
    - mod
    - helper
    - builder

##############################################
# +----------------------------------------+ #
# |          Chat Colour Settings          | #
# +----------------------------------------+ #
##############################################

chatcolour:
  # How many chat colour slots a player can save.
  slots: 3
  # Maximum amount of colours that can be used in a single save slot.
  colours: 3
  # Hex codes that players are not allowed to use.
  blacklisted-hexes:
  - "#000000"
  - "#050505"
  - "#0a0a0a"
  - "#111111"
  - "#1a1a1a"
  - "#202020"
  - "#2b2b2b"
  - "#333333"
  - "#0000aa"
  - "#aa0000"

##############################################
# +----------------------------------------+ #
# |                Language                | #
# +----------------------------------------+ #
##############################################

messages:
  prefix: "<bold><red>U</red><white>L</white> <gray>Cosmetics</gray> <dark_gray>»</dark_gray></bold> "
  reload: "<dark_green>Plugin reloaded."

  profile-exists: "<red>That player already has a cosmetic profile."
  profile-created: "<green>Successfully created a cosmetic profile for <bold><yellow>{player}</yellow></bold>."
  profile-deleted: "<green>Successfully deleted cosmetic profile for <bold><yellow>{player}</yellow></bold>."
  profile-reset: "<green>Successfully reset cosmetic profile for <bold><yellow>{player}</yellow></bold>."
  profile-not-found: "<red>No cosmetic profile found for <bold><yellow>{player}</yellow></bold>."

  prefix-profile-usage: "<red>Usage: /unitedcosmetics prefix [Save | Equip | Clear | Delete] [Username] [Slot] [Input]"
  prefix-cleared: "<green>Successfully cleared prefix for <bold><yellow>{player}</yellow></bold>."
  prefix-equipped: "<green>Successfully equipped custom prefix from slot <bold><yellow>{slot}</yellow></bold>."
  prefix-saved: "<green>Successfully saved and equipped your custom prefix to slot <bold><yellow>{slot}</yellow></bold>."
  prefix-slot-missing: "<red>Please specify a prefix slot."
  prefix-slot-invalid: "<red>Please specify a valid prefix slot."
  prefix-slot-empty: "<red>You do not have a prefix saved in that slot."
  prefix-slot-deleted: "<green>Successfully deleted prefix slot <bold><yellow>{slot}</yellow></bold> for <bold><yellow>{player}</yellow></bold>."
  prefix-invalid-text: "<red>Your prefix contains disallowed characters or words."
  prefix-invalid-length: "<red>Your prefix is too long. The maximum length is <bold><yellow>{length}</yellow></bold> characters."
  prefix-invalid-input: "<red>Missing input."

  chatcolour-profile-usage: "<red>Usage: /unitedcosmetics chatcolour [Save | Equip | Clear | Delete] [Username] [Slot] [HexCodes...]"
  chatcolour-cleared: "<green>Successfully cleared chat colour for <bold><yellow>{player}</yellow></bold>."
  chatcolour-equipped: "<green>Successfully equipped chat colour from slot <bold><yellow>{slot}</yellow></bold>."
  chatcolour-saved: "<green>Successfully saved and equipped your chat colour to slot <bold><yellow>{slot}</yellow></bold>."
  chatcolour-slot-missing: "<red>Please specify a chat colour slot."
  chatcolour-slot-invalid: "<red>Please specify a valid chat colour slot."
  chatcolour-slot-empty: "<red>You do not have a chat colour saved in that slot."
  chatcolour-slot-deleted: "<green>Successfully deleted chat colour slot <bold><yellow>{slot}</yellow></bold> for <bold><yellow>{player}</yellow></bold>."
  chatcolour-invalid-hex: "<red>Invalid or disallowed hex code provided."
  chatcolour-invalid-input: "<red>Missing input."

  # Settings for the /wardrobe menu.
  wardrobe-locked-item-suffix: " <dark_gray>[<#CB1D1D><bold>LOCKED</bold></#CB1D1D>]</dark_gray>"
  wardrobe-locked-item-description:
    - "<red><st>------------------------</st></red>"
    - "<#FFD644>ɪɴꜰᴏ</#FFD644>"
    - "<white>ᴘᴜʀᴄʜᴀꜱᴇ ᴛʜɪꜱ ᴄᴏꜱᴍᴇᴛɪᴄ ꜰʀᴏᴍ</white>"
    - "<#FFD644>/ꜱʜᴏᴘ</#FFD644> <white>ᴛᴏ ᴜɴʟᴏᴄᴋ</white>"
    - "<red><st>------------------------</st></red>"
  wardrobe-unlocked-item-description:
    - "<red><st>---------------------------</st></red>"
    - "           <#FFD644>ᴄʟɪᴄᴋ ᴛᴏ ᴇǫᴜɪᴘ</#FFD644>"
    - "<red><st>---------------------------</st></red>"
  wardrobe-equipped-item-description:
    - "<red><st>---------------------------</st></red>"
    - "<#FFD644>ɪɴꜰᴏ</#FFD644>"
    - "{cosmetic-type}"
    - "<red><st>---------------------------</st></red>"
    - "           <#FFD644>ᴄʟɪᴄᴋ ᴛᴏ ᴜɴᴇǫᴜɪᴘ</#FFD644>"
    - "<red><st>---------------------------</st></red>"
  wardrobe-category-name: "<#FFD644><bold>{category} Cᴏꜱᴍᴇᴛɪᴄꜱ</bold>"
  wardrobe-category-description:
    - "<red><strikethrough><bold>---------------------------</bold></strikethrough></red>"
    - "<#FFD644>ɪɴꜰᴏ"
    - "<white>ᴜɴʟᴏᴄᴋᴇᴅ: {unlocked}/{total}</white>"
    - "<red><strikethrough><bold>---------------------------</bold></strikethrough></red>"
    - "           <#FFD644>ᴄʟɪᴄᴋ ᴛᴏ ᴠɪᴇᴡ"
    - "<red><strikethrough><bold>---------------------------</bold></strikethrough></red>"
  wardrobe-button-name-back: "<#CB1D1D><bold>Bᴀᴄᴋ</bold>"
  wardrobe-button-name-previous: "<#FFD644><bold>Pʀᴇᴠɪᴏᴜꜱ Pᴀɢᴇ</bold>"
  wardrobe-button-name-next: "<#FFD644><bold>Nᴇxᴛ Pᴀɢᴇ</bold>"
  wardrobe-button-name-clear: "<#CB1D1D><bold>Uɴᴇǫᴜɪᴘ Aʟʟ</bold>"

  admin-profile-usage: "<red>Usage: /unitedcosmetics profile [Create | Delete | Reset] [Username]"
  no-permission: "<red>You do not have permission to perform this command."
  unknown-player: "<red>Unknown player."
